name: CI/CD Pipeline

on:
  push:
    branches:
        - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies and build Lambda package
      run: |
        python -m pip install --upgrade pip
        pip install requests
        mkdir package
        pip install --target ./package requests
        cd package && zip -r ../function.zip . && cd ..
        zip -g function.zip main.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Terraform Plan
      run: |
        cd terraform
        terraform init
        terraform plan -var-file="override.tfvars"

  apply:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform apply -var-file="override.tfvars" -auto-approve
